### ISSUE TITLE
:auto-die

### ISSUE THREAD

**Issue by FCO** [jonathanstowe/LibraryCheck#1]
That would be great if it accepts a auto-die adverb, that would throw a exception when couldn't load the library... Maybe accept the exception class as parameter

Thanks

**Comment by jonathanstowe** [comment]
That sounds like a sensible idea,  I'll take a look as soon as I can.

Thanks.

**Comment by jonathanstowe** [comment]
Hi,
for reasons of personal taste if made it ':exception'.  It will throw an X::NoLibrary if the library isn't found.

Thanks.

**Comment by FCO** [comment]
Thank you for the both fast replies! That was great! :exception is a good idea, another option that I had thought is :throws and possible :throws(X::AnotherException).
Thank you again!
Your modules are great!
