### ISSUE TITLE
Unexplained memory leak...

### ISSUE THREAD

**Issue by pprocacci** [jonathanstowe/LibraryCheck#3]
Somehow, the library-check routine leaks memory....and lots of it.

Tested on both Linux and FreeBSD.

+++++++++++++++++++++++++++++++++++++++++
use LibraryCheck;

sub MAIN()
{
  my Int $counter = 0;
  loop {
    if library-exists('libncurses.so') {
      say "libncurses.so";
    }
    sleep(1) if ++$counter % 1000 == 0;
  }
}

**Comment by jonathanstowe** [comment]
I'm pretty certain that the reason for this is that it creates a subroutine by eval every time it is called, which is not ideal but a better way to do this is not available until a fairly recent Rakudo and I have been holding off on merging the change.

I'll take a look to see if I can improve this.

**Comment by pprocacci** [comment]
I appreciate it.  I would have thought that $f would be cleaned up from memory (the stack?) upon subroutine completion.  To the naked eye (without knowing rakudo internals) I would have thought the code looks perfectly fine.

Regardless, I appreciate your attention to the matter.

**Comment by jonathanstowe** [comment]
Having done an experiment caching the sub between executions of the library-exists, it does seem that the creation of the sub like that does leak memory quite heavily, but that is not all of it,  I suspect that the library not found exception itself is leaking, I'll try to spin this into a rakudo issue separately but in the meantime I'm going to cache the whole result and see how that goes.

**Comment by jonathanstowe** [comment]
This has flat memory usage over hundreds of iterations.  It will of course use more if you test more libraries.
