### ISSUE TITLE
Tests failing against Rakudo HEAD

### ISSUE THREAD

**Issue by cfa** [jonathanstowe/LibraryCheck#4]
Encountered today using Rakudo HEAD (rakudo/rakudo@7e7aa26): The bogus library checks don't throw or error out as intended,

```
===> Testing: LibraryCheck:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
[LibraryCheck] # Failed test 'not ok for a bogus one'
[LibraryCheck] # at t/010-basic.t line 11
[LibraryCheck]     # Failed test 'code dies'
[LibraryCheck]     # at t/010-basic.t line 14
[LibraryCheck]     # You failed 1 test of 2
[LibraryCheck] # Failed test 'bogus one throws X::NoLibrary with :exception'
[LibraryCheck] # at t/010-basic.t line 14
[LibraryCheck] # You failed 2 tests of 4
===> Testing [FAIL]: LibraryCheck:ver<0.0.8>:auth<github:jonathanstowe>:api<1.0>
```

Reproduced on macOS and OpenBSD.

**Comment by jonathanstowe** [comment]
Eugh.  Thanks.  I'll take a look.

**Comment by jonathanstowe** [comment]
Confirmed on Linux with ```Rakudo version 2019.07.1-460-g044b33902 built on MoarVM version 2019.07.1-309-g48491b896```  investigating.

**Comment by jonathanstowe** [comment]
It appears that it's the 888a6b33806dc10150f0dbee32c3a66cf15e34e7 has stopped working.  Checking whether it needs fettling or whether just to revert for the time being.

**Comment by jonathanstowe** [comment]
Ah the https://github.com/rakudo/rakudo/commit/573f6a2ff2abe9ae8b6a5142b7fe5f400b651ba8 means simply applying the role isn't enough to make something a native sub.  Have adjusted the code with a temporary conditional so it will continue to work on older versions of Rakudo.
